services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3333:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - ./storage:/var/lib/mysql
    ports:
      - "3304:3306"  # Expose MySQL port to host
    networks:
      - app-network

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html:delegated
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
